[package]
name = "poker_solvers"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "~0.9.1"
# rs_poker = "~4.1.0"
thiserror = "~2.0.12" # for rs_poker core
serde = { version = "~1.0.219", features = ["derive", "serde_derive"] }
serde_json = "~1.0.140"
